In [1]:
import pandas as pd
import numpy as np

## Taxi

In [2]:
taxi_train = pd.read_csv(
    filepath_or_buffer = r'D:\Datasets\new-york-city-taxi-fare-prediction\train.csv',

    )
taxi_train

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
...,...,...,...,...,...,...,...,...
55423851,2014-03-15 03:28:00.00000070,14.0,2014-03-15 03:28:00 UTC,-74.005272,40.740027,-73.963280,40.762555,1
55423852,2009-03-24 20:46:20.0000002,4.2,2009-03-24 20:46:20 UTC,-73.957784,40.765530,-73.951640,40.773959,1
55423853,2011-04-02 22:04:24.0000004,14.1,2011-04-02 22:04:24 UTC,-73.970505,40.752325,-73.960537,40.797342,1
55423854,2011-10-26 05:57:51.0000002,28.9,2011-10-26 05:57:51 UTC,-73.980901,40.764629,-73.870605,40.773963,1
55423855,2014-12-12 11:33:00.00000015,7.5,2014-12-12 11:33:00 UTC,-73.969722,40.797668,-73.970885,40.783313,1

In [3]:
taxi_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55423856 entries, 0 to 55423855
Data columns (total 8 columns):
 #   Column             Dtype
---  ------             -----
 0   key                object
 1   fare_amount        float64
 2   pickup_datetime    object
 3   pickup_longitude   float64
 4   pickup_latitude    float64
 5   dropoff_longitude  float64
 6   dropoff_latitude   float64
 7   passenger_count    int64
dtypes: float64(5), int64(1), object(2)
memory usage: 3.3+ GB

In [4]:
taxi_train['pickup_datetime'] = pd.to_datetime(taxi_train['pickup_datetime'])
taxi_train['pickup_datetime']

0          2009-06-15 17:26:21+00:00
1          2010-01-05 16:52:16+00:00
2          2011-08-18 00:35:00+00:00
3          2012-04-21 04:30:42+00:00
4          2010-03-09 07:51:00+00:00
                      ...
55423851   2014-03-15 03:28:00+00:00
55423852   2009-03-24 20:46:20+00:00
55423853   2011-04-02 22:04:24+00:00
55423854   2011-10-26 05:57:51+00:00
55423855   2014-12-12 11:33:00+00:00
Name: pickup_datetime, Length: 55423856, dtype: datetime64[ns, UTC]

## accidents

In [44]:
accidents = pd.read_csv(
    filepath_or_buffer=r'D:\Datasets\UK_Accident\UK_Accident.csv',

).drop(columns=['Accident_Index', 'Unnamed: 0'])

accidents

,Location_Easting_OSGR,Location_Northing_OSGR,Longitude,Latitude,Police_Force,Accident_Severity,Number_of_Vehicles,Number_of_Casualties,Date,Day_of_Week,...,Pedestrian_Crossing-Physical_Facilities,Light_Conditions,Weather_Conditions,Road_Surface_Conditions,Special_Conditions_at_Site,Carriageway_Hazards,Urban_or_Rural_Area,Did_Police_Officer_Attend_Scene_of_Accident,LSOA_of_Accident_Location,Year
0,525680.0,178240.0,-0.191170,51.489096,1,2,1,1,04/01/2005,3,...,Zebra crossing,Daylight: Street light present,Raining without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002849,2005
1,524170.0,181650.0,-0.211708,51.520075,1,3,1,1,05/01/2005,4,...,Pedestrian phase at traffic signal junction,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002909,2005
2,524520.0,182240.0,-0.206458,51.525301,1,3,2,1,06/01/2005,5,...,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002857,2005
3,526900.0,177530.0,-0.173862,51.482442,1,3,1,1,07/01/2005,6,...,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Dry,NaN,NaN,1,Yes,E01002840,2005
4,528060.0,179040.0,-0.156618,51.495752,1,3,1,1,10/01/2005,2,...,No physical crossing within 50 meters,Darkness: Street lighting unknown,Fine without high winds,Wet/Damp,NaN,NaN,1,Yes,E01002863,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1504145,310037.0,597647.0,-3.417278,55.264773,98,2,2,1,07/12/2014,1,...,No physical crossing within 50 meters,Darkeness: No street lighting,Snowing without high winds,Snow,NaN,NaN,2,Yes,NaN,2014
1504146,321509.0,574063.0,-3.230255,55.054855,98,3,2,2,11/12/2014,5,...,No physical crossing within 50 meters,Darkeness: No street lighting,Fine without high winds,Snow,NaN,NaN,2,Yes,NaN,2014
1504147,321337.0,566365.0,-3.230826,54.985668,98,3,1,1,09/12/2014,3,...,No physical crossing within 50 meters,Darkness: Street lights present and lit,Fine without high winds,Frost/Ice,NaN,NaN,2,Yes,NaN,2014
1504148,323869.0,566853.0,-3.191397,54.990446,98,2,3,2,17/12/2014,4,...,No physical crossing within 50 meters,Darkeness: No street lighting,Raining without high winds,Wet/Damp,NaN,NaN,2,Yes,NaN,2014
1504149,314072.0,579971.0,-3.348426,55.106700,98,3,2,2,24/12/2014,4,...,No physical crossing within 50 meters,Daylight: Street light present,Fine without high winds,Wet/Damp,NaN,NaN,2,Yes,NaN,2014

In [45]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1504150 entries, 0 to 1504149
Data columns (total 31 columns):
 #   Column                                       Non-Null Count    Dtype
---  ------                                       --------------    -----
 0   Location_Easting_OSGR                        1504049 non-null  float64
 1   Location_Northing_OSGR                       1504150 non-null  float64
 2   Longitude                                    1504049 non-null  float64
 3   Latitude                                     1504150 non-null  float64
 4   Police_Force                                 1504150 non-null  int64
 5   Accident_Severity                            1504150 non-null  int64
 6   Number_of_Vehicles                           1504150 non-null  int64
 7   Number_of_Casualties                         1504150 non-null  int64
 8   Date                                         1504150 non-null  object
 9   Day_of_Week                                  1504150 non-null  int64
 10  Time                                         1504033 non-null  object
 11  Local_Authority_(District)                   1504150 non-null  int64
 12  Local_Authority_(Highway)                    1504150 non-null  object
 13  1st_Road_Class                               1504150 non-null  int64
 14  1st_Road_Number                              1504150 non-null  int64
 15  Road_Type                                    1504150 non-null  object
 16  Speed_limit                                  1504150 non-null  int64
 17  Junction_Control                             901315 non-null   object
 18  2nd_Road_Class                               1504150 non-null  int64
 19  2nd_Road_Number                              1504150 non-null  int64
 20  Pedestrian_Crossing-Human_Control            1504133 non-null  object
 21  Pedestrian_Crossing-Physical_Facilities      1504116 non-null  object
 22  Light_Conditions                             1504150 non-null  object
 23  Weather_Conditions                           1504150 non-null  object
 24  Road_Surface_Conditions                      1504150 non-null  object
 25  Special_Conditions_at_Site                   36582 non-null    object
 26  Carriageway_Hazards                          27250 non-null    object
 27  Urban_or_Rural_Area                          1504150 non-null  int64
 28  Did_Police_Officer_Attend_Scene_of_Accident  1504150 non-null  object
 29  LSOA_of_Accident_Location                    1395912 non-null  object
 30  Year                                         1504150 non-null  int64
dtypes: float64(4), int64(13), object(14)
memory usage: 355.7+ MB

In [50]:
target = accidents['Accident_Severity']
target = target.apply(lambda x: 1 if x >= 2 else 0)

data = accidents.drop(columns='Accident_Severity')

In [54]:
target.value_counts(normalize=True)

Accident_Severity
1    0.987075
0    0.012925
Name: proportion, dtype: float64